version: '3'

services:

  bankroot:
    image: bankroot-backend:0.0.1-SNAPSHOT
    build:
      context: .
    container_name: bankroot_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://app-db:5432/bank
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_SECURITY_JWT_KEY: ${JWT_KEY}
      Spring_SECURITY_JWT_NAME: ${JWT_NAME}
    depends_on:
      - app-db
    ports:
      - "8088:8080"

  app-db:
    image: postgres
    container_name: app-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bank
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local